config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :categories do
    resources :albums  
  end


  
  root "categories#index"

end

app/models/album.rb
class Album < ApplicationRecord

  belongs_to :category

  validates :title, presence: true
  validates :body, presence: true
  validates :artist, presence: true
  validates :release, presence: true


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :albums

  validates :title, presence: true, uniqueness: true

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    # get the category from the category_id, this is due to the config/routes.rb
    # as we have:
    # resources :categories do
    #   resources :albums
    # end
    @category = Category.find(params[:category_id])
    @album = Album.find(params[:id])
  end

  def new
    # get the category id
    @category = Category.find(params[:category_id])
    @album = @category.albums.new
  end
  
  def create
    # get the category id
    @category = Category.find(params[:category_id])
    
    # make a new album on this category
    @album = @category.albums.new(album_params)
    
    if @album.save
      redirect_to category_path(@category)
    else
      render "new"
    end
  end

  def album_params
    params.require(:album).permit(:title, :artist, :release, :body)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # List of categories/genres + home page
  def index
    @categories = Category.all
  end

  # New category/genre
  def new
    @category = Category.new
  end


  # Create a single category/genre
  def create
    @category = Category.new(params.require(:category).permit(:title))

    if @category.save
      redirect_to category_path(@category)
    else
      render "new"
    end
  end

  # Show a single category/genre
  def show
    @category = Category.find(params[:id])
  end


end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/albums/new.html.erb
<h1>Add an album</h1>

<%= simple_form_for [@category, @album] do |f| %>
<%= f.input :title %>
<%= f.input :artist %>
<%= f.input :release %>
<%= f.input :body %>

<%= f.button :submit, "Add album" %>
<% end %>

app/views/albums/show.html.erb
<h1>Album Page</h1>

<h3 class="album-title">
  album title
</h3>

app/views/categories/index.html.erb
<ul class="genre-list">
  <% @categories.each do |category| %>
  <li class="genre">
    <%= link_to category.title, category_path(category) %>
  </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>Add new genre!</h1>

<%= simple_form_for @category do |f| %>
<%= f.input :title %>

<%= f.button :submit, "Add genre" %>
<% end %>

app/views/categories/show.html.erb
<h1>
  <%= @category.title %>
</h1>

<% @category.albums.each do |album| %>

<h2><%= link_to album.title, category_album_path(@category, album) %></h2>

<%= simple_format album.body %>

<% end %>



<%= link_to "Add an album", new_category_album_path(@category) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PitchforkLite</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <header>
    <h1>
      <%= link_to "Pitchfork Lite", root_path %>
    </h1>
    <nav>
      <%= link_to 'Add Genre', new_category_path %>
      <a href="/">About</a>
      <a href="/">Blog</a>
    </nav>
  </header>
  <main>
    <%= yield %>
  </main>
</body>

</html>